### ISSUE TITLE
Remove Travis integration as duplicate to our GitHub Actions

### ISSUE THREAD

**Issue by jeffpaul** [10up/gutenbridge#16]
**Describe your question**
It looks like https://github.com/10up/convert-to-blocks/blob/develop/.travis.yml is duplicating what we're doing in https://github.com/10up/convert-to-blocks/blob/develop/.github/workflows/test.yml so I think we can remove the Travis integration and roll with the GitHub Actions for testing.  Yay?  Nay?

**Comment by dinhtungdu** [comment]
Agreed! Actually it's my mistake, I didn't remove travis in #6

**Comment by jeffpaul** [comment]
@dinhtungdu not your fault, Travis was added in after #6.
