### ISSUE TITLE
Save is executed too fast for gallery

### ISSUE THREAD

**Issue by mdesplenter** [10up/gutenbridge#170]
### Describe the bug

I have a site with old galleries that I wanted to convert to Gutenberg blocks. When clicking the Convert to blocks button in the admin it worked, but running this script it failed loading the images. After a lot of testing I found out that the save function is called directly and not giving the Gutenberg script enough time to modify all the images / content.

Adding the timeout around the save function fixed it for me:
https://github.com/10up/convert-to-blocks/blob/develop/assets/js/editor/editor.js#L69

```
setTimeout((function(){
client.save();
}),6000)
```

Takes more time, but better results for me.

### Steps to Reproduce

1. Add a gallery with multiple images in the old editor
2. Convert the post with the convert-to-blocks script
3. Images show up without a src

### WordPress information

Latest Wordpress, local, with Bedrock
Also tried without Bedrock.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@mdesplenter We have a PR up to fix this issue. If you have time to test that out and let us know if that fixes your issue, that would be great. Thanks!

**Comment by Sidsector9** [comment]
@dkotter the PR is not yet ready, I marked it as draft.

**Comment by Sidsector9** [comment]
@mdesplenter I've raised the PR, can you give it a try and let us know if it works for you? Thanks!
