### ISSUE TITLE
Not all "Convert to Blocks" links are processed

### ISSUE THREAD

**Issue by MadtownLems** [10up/gutenbridge#42]
Note: I originally reported this issue in the wordpress.org support forums (https://wordpress.org/support/topic/doesnt-seem-to-catch-all-classic-editor-blocks/), but conversation stalled and I wasn't sure if this is a more preferred avenue than there, so I'm reposting here.

**Describe the bug**
Not all "Convert to Blocks" links are processed.

**Steps to Reproduce**
1. Create a basic post that has the post_content from this gist: https://gist.github.com/MadtownLems/42b65929ec2000bbe338e8f3b99f533a

(2 columns, each with a freeform block in it).
2. Activate "Convert to Blocks"
3. Go to Edit the Post

**Expected behavior**
I expect the freeform/classic blocks to be converted into basic Paragraph blocks on page load.

**Screenshots**
(attached)
![2021-06-03 07_28_22-Window](https://user-images.githubusercontent.com/945157/120644798-59963f00-c43d-11eb-9bd7-f352ff8229ee.png)

**Environment information**
 - Device: Desktop PC
 - OS: Windows 10
 - Browser and version: Chrome 91
 - WordPress version: 5.7.2
 

Thank you so much for looking into this! I believe this plugin is going to be a HUGE timesaver as we start to migrate our content, but I don't think it's quite working for us as expected at this time. I'm more than happy to provide more details, try out new versions, or even jump on a call to discuss or work through things together. Cheers!

**Comment by jeffpaul** [comment]
Pinging @dsawardekar to help review if the Gutenberg raw handler had any significant changes in the latest releases.

**Comment by dsawardekar** [comment]
Thanks @MadtownLems. Your Bug report got truncated at,

> Create a basic post that has the post_content of

Can you create a gist with the original post_content?

**Comment by MadtownLems** [comment]
Oh sorry about that, I didn't realize.  Here's a gist with basic post content that edits as 2 Classic Editors when I would expect 'Convert to Blocks' to convert them into basic paragraph blocks:
https://gist.github.com/MadtownLems/42b65929ec2000bbe338e8f3b99f533a

**Comment by MadtownLems** [comment]
Howdy.
Just wanted to make sure you're able to view that gist alright, that it gives you what you need, and to see if there was anything else I could do to help look into this.
Cheers and thanks!

**Comment by dsawardekar** [comment]
@MadtownLems Apologies for the late reply. I was able to get this working with the current Gutenberg plugin (v10.9.0). 

https://github.com/10up/convert-to-blocks/pull/46

cc @jeffpaul

**Comment by MadtownLems** [comment]
No need to apologize - I sincerely appreciate your efforts here. Thanks!
It's unfortunate that it still doesn't work with the version shipped with WordPress. From your experience, does the Core version just lag a little bit behind the plugin? That is, is Convert to Blocks expected to work with WordPress 5.8 out of the box?

**Comment by dsawardekar** [comment]
@MadtownLems WordPress Core usually gets caught up with the stable Gutenberg version in a release or two. The timeline can vary based on the features in the release and/or any issues that come up. The process is documented here,

https://developer.wordpress.org/block-editor/contributors/code/release/#synchronizing-wordpress-trunk

**Comment by MadtownLems** [comment]
I'm testing Convert to Blocks 1.0.2 against WordPress 5.8 (no Gutenberg plugin) and noticed something very peculiar that I thought might be helpful (if not at least interesting)

You are correct that it does not immediately process Classic Editor Blocks that are inside of other blocks, BUT ... press F12 in Chrome to open the developer console, and then all those Classic Editor Blocks are processed! (without any other action required) 🤯

Not sure if there's any chance this gives a clue as to how to process them up front or not, but figured I'd share. Cheers!
