### ISSUE TITLE
Run the plugin automatically everytime a new posts is published

### ISSUE THREAD

**Issue by Webagent05** [10up/gutenbridge#45]
Dear M,

Great plugin, but I would like to configurate it run automatically after publishing a post with the classic editor.

Any suggestion how to approach this?

Thanks in advance.

Eno Mertens

**Comment by jeffpaul** [comment]
@Webagent05 theoretically there could be a hook to trigger that, but in that case why not just craft those posts in the block editor?

**Comment by bruvv** [comment]
Yes looking for this aswell, when using WP-automatic plugin, everything gets created in the classic editor...

**Comment by jeffpaul** [comment]
@bruvv I'm not familiar with that plugin, can you provide a direct link to it?  Also, I would be curious what you use that plugin for in place of the Block editor to better understand your use case?  Thanks!

**Comment by bruvv** [comment]
> 
> 
> @bruvv I'm not familiar with that plugin, can you provide a direct link to it? Also, I would be curious what you use that plugin for in place of the Block editor to better understand your use case? Thanks!

Sure here it is: https://codecanyon.net/item/wordpress-automatic-plugin/1904470
I am using it for posting about twitter releases and some youtube releases.

This is an example of what it is producing as a article:
```
<div>
<p>Lorium ipsum</p>
</div>
```

**Comment by jeffpaul** [comment]
@Webagent05 @bruvv what's the goal for having published posts get auto-converted to blocks?  Convert to Blocks will convert those posts if you go to edit them, so the first time you go to make an update to a published post it will get converted to the block editor.  Is there some case where you need that content in block editor format before you would be editing it?

**Comment by bruvv** [comment]
Just for uniformity :) so I can edit stuff on the fly more easier on my phone

**Comment by jeffpaul** [comment]
@bruvv are you using the iOS or Android app for WordPress or a webview of your WP Admin?

**Comment by bruvv** [comment]
webview, is the app any good? (i am on android)

**Comment by Webagent05** [comment]
@jeffpaul in my case: I'm importing content with an aggregator and this aggregator is not gutenberg compatible. Result one Classic editor block.
When converting to Gutenberg also a lot of crap imported in the html is filtered out. But now I need to edit each post to convert it. Would be handy if I could automatize this.

**Comment by jeffpaul** [comment]
@Webagent05 Convert to Blocks will convert that classic editor content to block editor content when you open those aggregator posts.  Is that not working for you or are you seeing issues with how the content is converted to blocks?

**Comment by Webagent05** [comment]
@jeffpaul The plugin works perfect, but I just don't want to open every post to convert. I want to bulk/automatize this handling.

**Comment by jeffpaul** [comment]
@Webagent05 what's the need to convert if you're not updating those posts?

**Comment by Webagent05** [comment]
@jeffpaul Main reason? When converting to blocks gutenberg removes certain html from the classic editor.
Sometimes I have posts breaking my design. When I convert them to Gutenberg blocks, it's solved. Also images are positioned better after converting to Gutenberg blocks.)

**Comment by bruvv** [comment]
Why all the questions 😂? Isn't it simple to add a button: convert all

**Comment by Webagent05** [comment]
@jeffpaul any time schedule for an update with this implementation.

**Comment by dinhtungdu** [comment]
@Webagent05 This plugin relies on the block editor to convert classic content to block content. So the conversion only happens when you open the classic content in the block editor.

If I understand correctly, you want the post to be converted to blocks automatically when it's created by your aggregator without any interaction with the block editor. Then this plugin can't do anything in that case.
