### ISSUE TITLE
Bulk conversion

### ISSUE THREAD

**Issue by jeffpaul** [10up/gutenbridge#56]
**Is your enhancement related to a problem? Please describe.**
As [noted on Twitter](https://twitter.com/boogah/status/1456030799829024768) (and in a couple other [dotorg](https://wordpress.org/support/topic/bulk-update-8/)/etc. places), some folks are requesting the ability to bulk convert posts vs. the one-at-a-time approach that C2B was built for.
> It works wonderfully, but there's no bulk conversion option. Anyone with more than a few hundred posts has got a ton of manual work ahead of them. CLI is *always* preferred (over a Bulk Edit dropdown on the All Posts table list view).

> Is there a way to to this function in bulk without having to open every single post?

**Describe the solution you'd like**
Initial approach is probably a CLI command as that limits the use to more technical users who we can gain initial feedback from before considering whether to expose this in a Bulk Edit dropdown option or not.

**Designs**
The CLI command could default to `all` posts in a specified post type, but accept a list or range of IDs to convert as an option?  Open to how we might structure the commend / input / output.

**Describe alternatives you've considered**

**Additional context**

**Comment by ActuallyConnor** [comment]
@jeffpaul I can take this on 😄

**Comment by ActuallyConnor** [comment]
What are the functions to call to convert a post to block?

**Comment by dsawardekar** [comment]
@ActuallyConnor Most of the transformation happens client-side in the Browser. This makes a WP CLI based solution difficult, as it has to match all the core & custom raw handling api's on the backend.

One way we have gotten around this limitation is by building a Puppeteer (or similar) script. The script works like this,

1. Load the Block Editor screen in the Admin (/wp-admin/post.php?post=N)
2. Wait for the Block Editor to finish transforming the classic editor blocks. (a second or two)
3. Hit the Update button to save the post to the BE.
4. Repeat for other post ids.

Hope that helps.

**Comment by conatus** [comment]
Hello all! 

Really impressed with this plugin so far and the "just in time" approach is a nice one. I also think batch processing would be really useful (for our use-case) and for that of the wider community.

However, as @dsawardekar notes, this spends on using client side code, in particular, looping over all the blocks on the page (after conversion) and running `rawHandler` over them, which is the set of transformations applied here - https://github.com/WordPress/gutenberg/tree/trunk/packages/blocks/src/api/raw-handling

Obviously you can run Javascript without a browser, but looking through this code in Gutenberg, a great deal depends on the browser environment existing. 

What one is tempted to do here is write an application in Javascript that queries the WordPress database and then uses these transformations directly on the HTML (if possible) then saves the results back out. This seems to break some pretty fundamental assumptions of this project, for example, that it is in PHP, with client-side Javascript.

Another approach would be to port a sub-set of these transformations to PHP. You could even use a PHP DOM manipulation library to port the code more quickly - handling the insertion of Gutenberg comments and so on.

I am not sure of the best way forward here, so would welcome everyone in the community throwing around ideas. Happy to try some experiments out and see how far we get!

**Comment by conatus** [comment]
Note this is also how the relatively popular Bulk Block Converter also operates, except this runs this using the WordPress API rather than loading it on the editor page.

https://github.com/ZamanehMedia/vo-bulk-block-converter/blob/f2aa48e5e9d4185cdd70fc8bc3b9c938beb3be8b/js/scripts.js#L166-L172

**Comment by conatus** [comment]
Also the way in which this plugin from Automattic works, though how the PHP elements operate isn't clear to me.

https://github.com/Automattic/newspack-content-converter/issues/97
