### ISSUE TITLE
Deactivates Gutenberg editor on custom post types not explicitly returning true from function hooked to `post_type_supports_convert_to_blocks` filter

### ISSUE THREAD

**Issue by adriantoll** [10up/gutenbridge#57]
**Describe the bug**
I have a site with pages and a series of custom post types. When I activate this plugin, any custom post types not explicitly returning `true` from a function hooked to the `post_type_supports_convert_to_blocks` filter have the Gutenberg editor completely deactivated and they revert to the classic editor.

**Steps to Reproduce**
1. Define a post type using `register_post_type()` that has `show_in_rest` set to `true`, so the Gutenberg editor is active for that post type.
2. Activate the plugin.
3. See that the custom post type has switched back to the classic editor from the Gutenberg editor.

**Expected behavior**
The plugin should not affect the Gutenberg editor on post types that do not return true from a function hooked to the `post_type_supports_convert_to_blocks` filter.

**Environment information**
 - Device: MacBook Pro
 - OS: 11.6.1
 - Browser and version: Chrome 96
 - WordPress version: 5.8.2
 - <details><summary>Site Health Info:</summary>
   I can't paste these here because the site is in development for a client. I would be happy to share specifics if necessary, but this should be easy to replicate as I've tested this on a vanilla WordPress 5.8.2 installation with no plugins or adjustments other than a single custom post type and this plugin.
   </details>

**Comment by dsawardekar** [comment]
@adriantoll Thanks for reporting this issue. I've identified this call as the cause of the issue,

https://github.com/10up/convert-to-blocks/blob/3a5c0662b8ca89f3666db597574eebe8027d6f63/includes/ConvertToBlocks/ClassicEditorSupport.php#L48

If the post_type_supports hook return is `false` it exits early. We'll add a new hook to the plugin to override this behavior. The if conditions will compute the return value and use a filter like below before returning from the `enable_block_editor` function. Something on the lines of,

```php
return apply_filters( 'convert_to_blocks_enable_block_editor', $result );

```

A workaround you can use right now is to override this behavior manually by adding a higher priority `use_block_editor_for_post` action hook. And then returning true for the respective post type. 

cc @jeffpaul

**Comment by adriantoll** [comment]
Thanks for the update @dsawardekar. I'm actually happy for this to run on all post types that use the block editor, so for now I've just manually listed those in the post_type_supports_convert_to_blocks hook.
