### ISSUE TITLE
unknown parameter on CLI command

### ISSUE THREAD

**Issue by norcross** [10up/gutenbridge#77]
### Describe the bug

when attempting to use the `--only` param on the CLI command, the standard "unknown parameter" is returned on the terminal. the `--post_type` param DOES work as expected.

### Steps to Reproduce

1. enter WP-CLI
2. enter the command `wp convert-to-blocks start --only=123,456,789` (changing IDs to ones that exist)
3. run the command

### Screenshots, screen recording, code snippet

![Screen Shot 2022-08-05 at 2 01 54 PM](https://user-images.githubusercontent.com/98561/183134602-97f96c86-f63e-49bf-a01b-d780f278505c.png)

### WordPress information

`
### wp-core ###

version: 6.0.1
site_language: en_US
user_language: en_US
timezone: America/New_York
permalink: /%year%/%monthnum%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: staging
user_count: 8
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /srv/www/nasadotgov/public_html
wordpress_size: loading...
uploads_path: /srv/www/nasadotgov/public_html/wp-content/uploads
uploads_size: loading...
themes_path: /srv/www/nasadotgov/public_html/wp-content/themes
themes_size: loading...
plugins_path: /srv/www/nasadotgov/public_html/wp-content/plugins
plugins_size: loading...
database_size: loading...
total_size: loading...

### wp-active-theme ###

name: NASA (nasa)
version: 1.1.1
author: Lone Rock Point
author_website: https://lonerockpoint.com/
parent_theme: none
theme_features: widgets-block-editor, disable-custom-font-sizes, editor-font-sizes, disable-custom-colors, editor-color-palette, automatic-feed-links, editor-styles, align-wide, title-tag, post-thumbnails, menus, html5, custom-background, customize-selective-refresh-widgets, custom-logo
theme_path: /srv/www/nasadotgov/public_html/wp-content/themes/nasa

### wp-themes-inactive (3) ###

NASA 2021 PBrocks: version: 1.3.6, author: pbrocks
Twenty Twenty-One: version: 1.1, author: the WordPress team (latest version: 1.6)
Twenty Twenty-Two: version: 1.1, author: the WordPress team (latest version: 1.2)

### wp-mu-plugins (38) ###

Admin Notice: version: 0.1.0, author: WordPress VIP
Advanced Post Caching: version: 0.2, author: Automattic
Akismet Anti-Spam: version: 4.2.4, author: Automattic
Async Publish Actions: author: Automattic, version: (undefined)
blogpublic-notice.php: author: (undefined), version: (undefined)
Cron Control: version: 3.1, author: Erick Hitter, Automattic
Debug Bar: version: 1.1.3, author: wordpressdotorg
HTTP Concat: version: 1.0, author: Automattic
Jetpack: version: 10.9, author: Automattic
Lightweight Term Count Update: version: 0.1.0, author: Automattic, Alley Interactive
Query Monitor: version: 3.8.2, author: John Blackbourn
REST API Enhancements: version: 0.1, author: Erick Hitter, Automattic
Rewrite Rules Inspector: version: 1.3.1, author: Automattic, Daniel Bachhuber
VaultPress: version: 2.2.1, author: Automattic
VIP AllOptions Safeguard: author: Automattic, version: (undefined)
VIP Back-compat: version: 1.0, author: Automattic
VIP Cache Manager: version: 1.1, author: Automattic
VIP Client mu-plugins: author: Automattic, version: (undefined)
VIP Codebase Manager: version: 1.0.0, author: Automattic
VIP Dashboard: version: 3.0.0, author: Scott Evans, Filipe Varela, Pau Argelaguet
VIP Feed Cache: author: Automattic, version: (undefined)
VIP File Service: version: 0.2, author: Automattic
VIP Force Two Factor: author: Automattic, version: (undefined)
VIP Go Core Modifications: author: Automattic, version: (undefined)
VIP Go Plugin Compat: version: 1.0, author: Automattic
VIP Hosting Miscellaneous: version: 1.1, author: Automattic
VIP Init: author: Automattic, version: (undefined)
VIP Mail: version: 1.0, author: Automattic
VIP Parse.ly Integration: version: 1.0, author: Automattic
VIP Performance: version: 1.0, author: Automattic
VIP Plugins: version: 1.0.0, author: Automattic
VIP Schema: author: Automattic, version: (undefined)
VIP Security: version: 1.2, author: Automattic
VIP Stats: author: Automattic, version: (undefined)
WooCommerce: VIP Specific Changes: version: 1.0.0, author: Automattic
WordPress Importer: version: 0.6.4, author: wordpressdotorg
WordPress VIP Support: version: 3.1.0, author: <a href="http://automattic.com">Automattic</a>
WP-CLI for VIP Go: author: Automattic, version: (undefined)

### wp-plugins-active (15) ###

CMB2: version: 2.10.1, author: CMB2 team
Co-Authors Plus: version: 3.5.2, author: Mohammad Jangda, Daniel Bachhuber, Automattic
Convert to Blocks: version: 1.1.0, author: 10up
F4 Media Taxonomies: version: 1.1.1, author: FAKTOR VIER
NASA Dashboard Manager: version: 0.0.1-dev, author: Lone Rock Point
NASA Data Migration: version: 0.0.1-dev, author: Lone Rock Point
NASA Gutenberg Blocks: version: 2.3.1, author: Lone Rock Point
NASA Horizon Design System Core Setup: version: 0.0.1-dev, author: Lone Rock Point
NASA User Role Scoping: version: 0.0.1-dev, author: Lone Rock Point
Newspack Content Converter Forked: version: 11.11.1970, author: Automattic / Norcross
OneLogin SAML SSO: version: 3.4.0, author: OneLogin, Inc.
Public Post Preview: version: 2.9.3, author: Dominik Schilling
Safe SVG: version: 2.0.2, author: 10up
Simple Local Avatars: version: 2.5.0, author: Jake Goldman, 10up
WP-Sweep: version: 1.1.5, author: Lester 'GaMerZ' Chan

### wp-plugins-inactive (14) ###

Accessibility Checker: version: 1.2.11, author: Equalize Digital (latest version: 1.2.12)
Accessibility Checker Pro: version: 1.1.6, author: Equalize Digital
Admin Columns Pro: version: 5.7.2, author: AdminColumns.com
Gravity Forms: version: 2.4.24, author: Gravity Forms
Gravity Forms Quiz Add-On: version: 3.7, author: Gravity Forms
JSM's Show Post Metadata: version: 3.0.4, author: JS Morisset
JSM's Show User Metadata: version: 3.0.4, author: JS Morisset
NASA Editorial Content Pitch: version: 0.0.1-dev, author: Lone Rock Point
NASA Training Site Setup: version: 0.0.1-dev, author: Lone Rock Point
Post Type Switcher: version: 3.2.1, author: Triple J Software, Inc.
Pre-Publish Checklist: version: 1.1.1, author: Brainstorm Force
Rank Math SEO: version: 1.0.92.1, author: Rank Math (latest version: 1.0.94)
Rank Math SEO PRO: version: 3.0.15, author: Rank Math
Regenerate Thumbnails: version: 3.1.5, author: Alex Mills (Viper007Bond)

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 1024M
upload_max_filesize: 1024M
max_effective_size: 1 GB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DNG, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMV, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.4.0-91-generic x86_64
httpd_software: nginx/1.23.0
php_version: 8.0.21 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 300
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 1024M
php_post_max_size: 1024M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true

### wp-database ###

extension: mysqli
server_version: 10.5.16-MariaDB-1:10.5.16+maria~focal
client_version: mysqlnd 8.0.21
max_allowed_packet: 134217728
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /srv/www/nasadotgov/public_html/wp-content
WP_PLUGIN_DIR: /srv/www/nasadotgov/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: staging
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### jetpack ###

site_id: false
ssl_cert: No
time_diff: false
version_option: 9.4.1:1614723894
old_version: 9.4.1:1614723894
public: Private
master_user: No master user set.
current_user: #1 norcross
tokens_set: None
blog_token: Not set.
user_token: Not set.
version: 10.9
jp_plugin_dir: /srv/www/nasadotgov/public_html/wp-content/mu-plugins/jetpack-10.9/
plan: free
protect_header: false
full_sync: {"started":"Thu, 01 Jan 1970 00:00:00 +0000","finished":"Thu, 01 Jan 1970 00:00:00 +0000","progress":[],"config":[]}
sync_size: undefined
sync_lag: 0 seconds
full_sync_size: undefined
full_sync_lag: 0 seconds
idc_urls: {"home":"http:\/\/nasadotgov.test","siteurl":"http:\/\/nasadotgov.test","WP_HOME":"","WP_SITEURL":""}
idc_error_option: false
idc_optin: true
cxn_tests: All Pass.

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dsawardekar** [comment]
Thanks for the detailed feedback @norcross! There was a bug in the help text, Fixed here, https://github.com/10up/convert-to-blocks/pull/78.
